trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Hosted agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd hello_app
    export FLASK_APP=webapp.py
    flask run --host=0.0.0.0 --port=5000
  displayName: 'Run Flask app (Linux)'
  condition: succeeded()
