trigger:
- main

pool:
  name: SelfHostedPool  # Change this to your actual agent pool name if different

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd hello_app
    set FLASK_APP=webapp.py
    flask run
  displayName: 'Run Flask app (Windows)'
  condition: succeeded()
